package_assets:         on          # (on, off, always)
compress_assets:        on          # (on, off)
gzip_assets:            on          # (on, off)
package_path:           bundles     # (defaults to assets)
javascript_compressor:  closure          # (yui, closure)
compressor_options:
  compilation_level: "WHITESPACE_ONLY"

javascripts:
  main:
    - js/app.js